<a href="https://colab.research.google.com/github/KuoZiyun/Python/blob/main/Python%E4%BD%9C%E6%A5%AD4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
params = {
    'tickers':['2330.TW','2303.TW','2454.TW','2317.TW','2337.TW'],
    'start':'2025-01-01',
    'end':'2025-11-11',
    'interval':'1d'
}

In [ ]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (3.18.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.5)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2025.10.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.23)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

In [ ]:
import yfinance as yf
data = yf.download(**params)
data.tail()

/tmp/ipython-input-1577927734.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(**params)
[*********************100%***********************]  5 of 5 completed

Price           Close                                          High          \
Ticker        2303.TW 2317.TW 2330.TW    2337.TW 2454.TW    2303.TW 2317.TW
Date
2025-11-04  47.400002   244.0  1505.0  29.700001  1315.0  48.750000   255.0
2025-11-05  47.099998   247.0  1460.0  31.350000  1330.0  47.099998   248.5
2025-11-06  45.799999   248.0  1465.0  34.450001  1290.0  47.750000   250.5
2025-11-07  45.000000   244.0  1460.0  35.250000  1260.0  45.599998   250.5
2025-11-10  45.200001   249.5  1475.0  37.900002  1250.0  45.650002   250.0

Price                                  ...       Open                  \
Ticker     2330.TW    2337.TW 2454.TW  ...    2303.TW 2317.TW 2330.TW
Date                                   ...
2025-11-04  1525.0  31.250000  1315.0  ...  48.750000   252.0  1520.0
2025-11-05  1485.0  31.600000  1330.0  ...  47.099998   239.0  1480.0
2025-11-06  1480.0  34.450001  1330.0  ...  47.750000   249.5  1470.0
2025-11-07  1465.0  36.000000  1295.0  ...  45.500000   246.0  1460.0
2025-11-10  1485.0  38.500000  1260.0  ...  45.500000   245.0  1470.0

Price                            Volume                                  \
Ticker        2337.TW 2454.TW   2303.TW    2317.TW   2330.TW    2337.TW
Date
2025-11-04  31.150000  1290.0  65151205   91077032  33925673  111160757
2025-11-05  28.799999  1295.0  48037302  111699424  56305422  135847681
2025-11-06  31.850000  1320.0  60365518   64418664  27411394  294060962
2025-11-07  34.349998  1285.0  33263691   48667340  20329390  366325111
2025-11-10  36.000000  1250.0  22981297   50699016  25281744  373760141

Price
Ticker      2454.TW
Date
2025-11-04  6324011
2025-11-05  6722398
2025-11-06  7307681
2025-11-07  7288497
2025-11-10  5195821

[5 rows x 25 columns]

In [ ]:
name_map = {'2330.TW': '台積電',
            '2303.TW': '聯電',
            '2454.TW': '聯發科',
            '2317.TW': '鴻海',
            '2337.TW': '旺宏'}

In [ ]:
sector = {'2330.TW':'半導體',
          '2303.TW':'半導體',
          '2454.TW':'半導體',
          '2317.TW':'電子代工',
          '2337.TW':'半導體'}

In [ ]:
import pandas as pd
df = pd.DataFrame({'tickers':['2330.TW','2303.TW','2454.TW','2317.TW','2337.TW']})
df['中文名'] = df['tickers'].map(name_map)
df['產業'] = df['tickers'].map(sector)
df

   tickers  中文名    產業
0  2330.TW  台積電   半導體
1  2303.TW   聯電   半導體
2  2454.TW  聯發科   半導體
3  2317.TW   鴻海  電子代工
4  2337.TW   旺宏   半導體

In [ ]:
default_paramas = {'start':'2025.01.01',
                   'end':'2025.11.11',
                   'interval':'1d'}

custom_paramas = {**default_paramas,
                  'tickers':['2330.TW','2303.TW','2454.TW','2317.TW','2337.TW']}

custom_paramas

{'start': '2025.01.01',
 'end': '2025.11.11',
 'interval': '1d',
 'tickers': ['2330.TW', '2303.TW', '2454.TW', '2317.TW', '2337.TW']}